### ISSUE TITLE
Duplicated ship models in API response when filter "sorts":"fallback_pledge_price" is on

### ISSUE THREAD

**Issue by MarvinMiles** [fleetyards/fleetyards#344]
Hi mortik!

https://api.fleetyards.net/v1/models?q=%7B%22sorts%22:%22fallback_pledge_price%22%7D&page=1&perPage=10

**Page 1**: Last ship in response:
```
{
"id": "db812510-5812-4a03-9f64-3e3911e7bed1",
"name": "Dragonfly Yellowjacket",
....
}
```

https://api.fleetyards.net/v1/models?q=%7B%22sorts%22:%22fallback_pledge_price%22%7D&page=2&perPage=10

**Page 2**: First ship in response is the same:
```
{
"id": "db812510-5812-4a03-9f64-3e3911e7bed1",
"name": "Dragonfly Yellowjacket",
....
}
```

**Comment by mortik** [comment]
Hey,

the problem with this is you are sorting on a field which non unique values. Since you are sorting only the ```fallback_pledge_price``` every entry with for example ```40``` will be random sorted. This is why in this edge case you are getting duplicated entries, the other thing that have happened are missing entries.

I added a Pull Request #348 to add a more robust fallback for this case
